### ISSUE TITLE
Add twitter feed to frontpage

### ISSUE THREAD

**Issue by nielsdrost** [nl-rse/nl-rse.github.io#5]
To show some recent activity we should add a twitter feed to our frontpage:

I suggest we show the timeline for the nl_rse twitter account: https://twitter.com/nl_rse

See how to do this here: https://publish.twitter.com/#

**Comment by benvanwerkhoven** [comment]
I've add a twitter bar in my fork, you can preview the work here: https://benvanwerkhoven.github.io/nl-rse.github.io/
We do need some more activity though, the last tweet is from September.

**Comment by nielsdrost** [comment]
Looks great! Agree we need some recent activity.

@mkuzak could you look into the twitter feed? If needed we can find a few more people to help out.

**Comment by sbranchett** [comment]
I'm retweeting once a week now. Should we close the issue?

**Comment by nielsdrost** [comment]
Sounds good to me!

**Comment by benvanwerkhoven** [comment]
Great! I'll close the issue.
