### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by nielsdrost** [nl-rse/nl-rse.github.io#8]
This repo needs a LICENSE.md :-)

**Comment by nielsdrost** [comment]
Any thoughts on a code license (e.g. APACHE 2) vs a content license (e.g. CC-BY)?

**Comment by benvanwerkhoven** [comment]
I'm perfectly fine with using CC-BY for this. I'll add a file.

**Comment by bast** [comment]
Thank you very much! Does the CC-BY also cover the source code part? I am not a super expert on licenses but often I see CC licenses covering the "content" part and one of the code licenses the source code part. I don't want to over-complicate this however. @rlonka

**Comment by benvanwerkhoven** [comment]
Well, we've hardly written any source code for this site. Most of it is just plain 'minima', which has MIT License (https://github.com/jekyll/minima). We've only changed the colors and inserted a few things like a logo and a twitter bar, nothing to worry about.

**Comment by bast** [comment]
OK. Thank you again :-)
